### ISSUE TITLE
TODO before release

### ISSUE THREAD

**Issue by janis91** [janis91/pdf_tailor#1]
- [x]  add translation integration
- [x]  add app to app store
- [x]  add travis ci project
- [x] add secrets to travis ci
- [x]  codacy settings

**Comment by janis91** [comment]
https://github.com/nextcloud/app-certificate-requests/pull/288

**Comment by janis91** [comment]
mention morrisjobke when initial app code is ready (for translation setup)
